name: VirtualFlightThrottle
description: Customizable Virtual Flight-Throttle&#x2F;Controller

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1

  flutter_speed_dial: ^1.2.5

  card_settings: ^1.5.3

  sqflite: ^1.2.0

  path_provider: ^1.5.1

  ping_discover_network: ^0.2.0+1

  vibrate: ^0.0.4

  async: ^2.3.0

  connectivity: ^0.4.6+2

  flutter_xlider: 3.0.0

  fluttertoast: ^3.1.3

  control_pad: ^1.0.1+1

  dotted_border: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/jsons/