name: VirtualFlightThrottle
description: Customizable Virtual Flight-Throttle&#x2F;Controller

version: 1.0.2+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1

  flutter_speed_dial: ^1.2.5

  card_settings: ^1.16.2

  sqflite: ^1.2.0

  path_provider: ^1.5.1

  connectivity: ^2.0.2

  wifi_info_flutter: ^1.0.3

  ping_discover_network: ^0.2.0+1

  flutter_vibrate: ^1.0.0

  async: ^2.3.0

  flutter_xlider: 3.0.0

  fluttertoast: ^3.1.3

  control_pad: ^1.0.1+1

  dotted_border: ^1.0.4

  url_launcher: ^5.4.1

  intl_utils: ^1.0.2

  wakelock: ^0.1.4+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/jsons/
  - assets/images/

flutter_intl:
  enabled: true