name: VirtualFlightThrottle
description: Customizable Virtual Flight-Throttle&#x2F;Controller

version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_speed_dial: ^1.2.5

  card_settings: ^1.5.3

  cupertino_icons: ^0.1.2

  sqflite: ^1.2.0

  path_provider: ^1.5.1

  ping_discover_network: ^0.2.0+1

  vibration: 1.2.2

  async: ^2.3.0

  connectivity: ^0.4.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true